# Generated by Django 6.0 on 2025-12-30 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('release_year', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('duration', models.CharField(default='0hrs 0mins', max_length=200)),
                ('director', models.CharField(max_length=200)),
            ],
        ),
    ]
